"""
Django settings for tosdiff project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-@dfo8(-%uzm&3+m9^u+ifrl&-4+ys3hd1r=#r#jo3!bg^1im@*",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()] or (["*"] if DEBUG else [])

# Render terminates TLS at its edge and forwards requests to the container
# over plain HTTP; without this Django would treat requests as insecure and
# reject the browser's https Origins on POSTs (CSRF failures behind the proxy).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Permit the browser's https Origin/Referer on POSTs for every allowed host.
CSRF_TRUSTED_ORIGINS = [
    f"{scheme}://{host}" for host in ALLOWED_HOSTS if host != "*" for scheme in ("https", "http")
]

# HTTPS-only in production. TLS is terminated by Render's edge, so the
# container sees the forwarded-proto header set above; the cookie/redirect
# settings below only apply once DEBUG is off (never during local dev).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # one year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_REFERRER_POLICY = "same-origin"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "monitor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tosdiff.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "monitor.context_processors.sponsor_links",
                "monitor.context_processors.last_updated",
            ],
        },
    },
]

WSGI_APPLICATION = "tosdiff.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def database_config_from_url(database_url: str) -> dict:
    """Build a Django DATABASES entry from a Postgres URL.

    Query parameters (e.g. ``sslmode=require``) are forwarded verbatim to
    ``OPTIONS`` so Render's TLS requirement works straight from the URL.
    Leading/trailing whitespace and wrapping quotes are stripped first so a
    URL pasted from a dashboard is accepted as-is.
    """
    parsed = urlparse(database_url.strip().strip("\"'"))
    options = {key: values[-1] for key, values in parse_qs(parsed.query).items()}
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/"),
        "USER": parsed.username or "",
        "PASSWORD": parsed.password or "",
        "HOST": parsed.hostname or "localhost",
        "PORT": str(parsed.port or 5432),
        "OPTIONS": options,
    }


_database_url = os.environ.get("DATABASE_URL", "")
_db_engine = os.environ.get("DB_ENGINE", "sqlite3")

if _database_url:
    DATABASES = {"default": database_config_from_url(_database_url)}
elif _db_engine == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "tosdiff"),
            "USER": os.environ.get("DB_USER", "tosdiff"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

STATIC_ROOT = BASE_DIR / "staticfiles"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Email — Mailgun for transactional mail, SMTP for admin/ops mail
# ---------------------------------------------------------------------------
# Django 6.1's MAILERS multiplexer routes each email type to its own backend:
#   * "default" — user-facing transactional mail (OTP login codes, suggestion
#     replies, daily/weekly digests) via Mailgun's HTTP API.
#   * "admin"   — Django error reports plus mail_admins()/mail_managers()
#     calls; these keep using the SMTP server configured below.
# When MAILGUN_API_KEY is unset (local dev), the default mailer falls back to
# the console backend; admin mail always uses the SMTP settings.
# Note: defines MAILERS, so the legacy EMAIL_BACKEND/EMAIL_HOST/... settings
# must NOT be set (Django 6.1 rejects them when MAILERS is defined).
MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY", "")
MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN", "")
MAILGUN_API_URL = os.environ.get("MAILGUN_API_URL", "https://api.mailgun.net")
MAILGUN_TIMEOUT = int(os.environ.get("MAILGUN_TIMEOUT", "30"))

_default_mailer_backend = (
    "monitor.emailing.MailgunBackend"
    if MAILGUN_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)

MAILERS = {
    "default": {
        "BACKEND": _default_mailer_backend,
        "OPTIONS": {},
    },
    "admin": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "OPTIONS": {
            "host": os.environ.get("EMAIL_HOST", "localhost"),
            "port": int(os.environ.get("EMAIL_PORT", "25")),
            "username": os.environ.get("EMAIL_HOST_USER", ""),
            "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
            "use_tls": os.environ.get("EMAIL_USE_TLS", "false").lower() in ("1", "true", "yes"),
            "use_ssl": os.environ.get("EMAIL_USE_SSL", "false").lower() in ("1", "true", "yes"),
            "timeout": int(os.environ.get("EMAIL_TIMEOUT", "30")),
        },
    },
}

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "TosDiff <no-reply@tosdiff.local>")

# Admin/ops mail recipients — Django error reports are sent to these
# addresses (list of email address strings).
admin_emails = [
    e.strip() for e in os.environ.get("DJANGO_ADMIN_EMAILS", "").split(",") if e.strip()
]
ADMINS = admin_emails
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", "TosDiff Admin <admin@tosdiff.local>")

# Absolute base URL used when building links in emails sent from Celery tasks.
BASE_URL = os.environ.get("BASE_URL", "http://localhost:8000")

# Funding links shown in the site footer ("Support TosDiff" buttons). Leave
# empty to hide the section entirely (e.g. local dev or once costs are covered).
SPONSOR_GITHUB_URL = os.environ.get("SPONSOR_GITHUB_URL", "")
SPONSOR_KOFI_URL = os.environ.get("SPONSOR_KOFI_URL", "")


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
_redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True

# Retry settings
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Celery Beat — periodic tasks
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "check-all-documents-daily": {
        "task": "monitor.tasks.check_all_documents",
        "schedule": crontab(hour=2, minute=0),  # 02:00 UTC daily
    },
    "send-daily-digests": {
        "task": "monitor.tasks.send_daily_digests",
        "schedule": crontab(hour=9, minute=0),  # 09:00 UTC daily
    },
    "send-weekly-digests": {
        "task": "monitor.tasks.send_weekly_digests",
        "schedule": crontab(hour=9, minute=0, day_of_week="monday"),  # 09:00 UTC Mondays
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "admin_email": {
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "level": "ERROR",
            # Route 500 error reports over SMTP through the mailers
            # subsystem ("admin" mailer) — transactional mail stays on Mailgun.
            "using": "admin",
            "include_html": True,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "monitor": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Without this, Django's default logging config isn't applied, so
        # request errors (500s) would never reach the AdminEmailHandler.
        "django": {
            "handlers": ["console", "admin_email"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
