# Generated by Django 6.0.5 on 2026-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='custom_selectors',
            field=models.TextField(blank=True, default='', help_text='CSS selectors to exclude before text extraction, one per line. Example: .cookie-banner\n#sidebar'),
        ),
    ]
