# Generated by Django 6.0.5 on 2026-05-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_language_document_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='other_document_type',
            field=models.CharField(blank=True, default='', help_text='Describe the document type when "Other" is selected.', max_length=255),
        ),
    ]
