# Generated by Django 6.0.5 on 2026-05-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_payment_service_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_format',
            field=models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('txt', 'TXT')], default='html', help_text='Format of the fetched document (set automatically during fetch).', max_length=10),
        ),
    ]
