# Generated by Django 5.2.16 on 2026-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_add_organization_category_and_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_failing',
            field=models.BooleanField(default=False, help_text='Set to True if this document is consistently failing to fetch.'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Custom name for this document. If blank, the category will be used.', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_failing',
            field=models.BooleanField(default=False, help_text="Set to True if this organization's documents are consistently failing to fetch."),
        ),
    ]
