# Generated by Django 6.1 on 2026-09-24 01:15

from django.db import migrations, models


def convert_immediate_to_daily(apps, schema_editor):
    """Move any users on the now-removed 'immediate' setting to the daily default."""
    NotificationPreference = apps.get_model("monitor", "NotificationPreference")
    NotificationPreference.objects.filter(frequency="immediate").update(frequency="daily")


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0013_suggestion_user_and_digests"),
    ]

    operations = [
        migrations.RunPython(convert_immediate_to_daily, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notificationpreference",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Daily digest"), ("weekly", "Weekly digest")],
                default="daily",
                help_text="Batch change emails into a daily or weekly digest.",
                max_length=10,
            ),
        ),
    ]
