# Generated by Django 6.1.1 on 2026-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0014_remove_immediate_notification_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fetch_config",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Optional Playwright fetch configuration. Keys: wait_for_selector (CSS selector to wait for), sleep_seconds (extra wait time for JS rendering), dismiss_selectors (list of CSS selectors for cookie/modal buttons to click), challenge_timeout (seconds to wait for a Cloudflare verification challenge to auto-resolve; default 30).",
                null=True,
            ),
        ),
    ]
