# Generated by Django 6.1 on 2026-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0015_update_fetch_config_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fetch_method",
            field=models.CharField(
                choices=[
                    ("requests", "HTTP Requests"),
                    ("playwright", "Playwright (headless browser)"),
                    ("playwright_browser", "Playwright (real browser User-Agent)"),
                ],
                default="requests",
                max_length=20,
            ),
        ),
    ]
