# Generated by Django 6.1 on 2026-09-26 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0016_playwright_browser_fetch_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["organization__name", "name", "document_type"]},
        ),
    ]
