# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0017_document_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology & Software"),
                    ("social_media", "Social, Search & Advertising"),
                    ("gaming", "Gaming & Interactive Entertainment"),
                    ("entertainment_streaming", "Entertainment & Streaming"),
                    ("media", "Media, News & Publishing"),
                    ("food_delivery", "Food Delivery & Local Services"),
                    ("retail", "Retail & E-Commerce"),
                    ("airlines_travel", "Airlines & Travel"),
                    ("hospitality", "Hospitality & Hotels"),
                    ("banking", "Banking & Lending"),
                    ("investments", "Investments & Asset Management"),
                    ("insurance", "Insurance"),
                    ("healthcare", "Healthcare & Pharmaceuticals"),
                    ("education", "Education & Online Learning"),
                    ("nonprofit", "Nonprofit & Foundation"),
                    ("government", "Government & Public Sector"),
                    ("utilities", "Utilities & Energy"),
                    ("automotive", "Automotive & Transportation"),
                    ("telecom", "Telecommunications"),
                    ("professional_services", "Professional & Consulting Services"),
                    ("logistics", "Logistics & Shipping"),
                    ("other", "Other"),
                ],
                default="",
                help_text=(
                    "Primary industry for this organization. Use tags for cross-industry traits."
                ),
                max_length=50,
            ),
        ),
    ]
